### ISSUE TITLE
Icon

### ISSUE THREAD

**Issue by garrett** [allisonkarlitskaya/boxi#2]
Inspiration: Boxhagener Platz, in Berlin

https://www.openstreetmap.org/#map=19/52.51078/13.45957

![image](https://user-images.githubusercontent.com/10246/177118094-fcd63e6d-90b1-4ae3-a147-a7c94c21742b.png)

https://www.google.com/maps/place/Boxhagener+Platz/@52.5108668,13.4595849,240m/data=!3m2!1e3!4b1

![image](https://user-images.githubusercontent.com/10246/177118047-0741aa80-3245-434f-b5d3-064a976d4c3c.png)

Here's a highly abstract version with colors of the components of the "square" rounded to GNOME colors, attempting to adhere to the GNOME Icon design guidelines:

![image](https://user-images.githubusercontent.com/10246/177118361-008c8d41-7710-49ae-bb5f-48d88cc28d04.png)
 
Source SVG: 
![org.boxi.Boxi Source](https://user-images.githubusercontent.com/10246/177118523-289dd76e-ddeb-4fe3-be48-b069a50990a2.svg)

Icon SVG:
![org boxi Boxi](https://user-images.githubusercontent.com/10246/177118678-a1feff22-24a1-470b-967c-3b87880bbaf6.svg)

Devel icon SVG:
![org boxi Boxi Devel](https://user-images.githubusercontent.com/10246/177118669-7eaca98d-f722-401f-83bb-bcec6748c64c.svg)

Symbolic icon SVG:
![org boxi Boxi-symbolic](https://user-images.githubusercontent.com/10246/177118664-5ff80fa6-e30c-4e35-af9b-96ad2b756da3.svg)

**Comment by garrett** [comment]
I did try the slightly rotated version, but it didn't work, as:

1. There's some weird rendering/clipping problem (which I could probably work around, really)
2. It's suddenly way out of place with the rest of the icons
3. It doesn't really work well with the text label

![image](https://user-images.githubusercontent.com/10246/177119853-96ddfd1f-4ec0-49e7-8792-b56c498dc218.png)

**Comment by allisonkarlitskaya** [comment]
I like the rotation :)

I defer to you here, though.

Do you want to do a PR?  The layout of the files in the tree should be pretty obvious, and there's nothing else you need to touch.

**Comment by garrett** [comment]
Minor tweaks.

![image](https://user-images.githubusercontent.com/10246/177123776-eb7a4b9e-93f7-4116-9e50-608300c05724.png)


![org boxi Boxi Source](https://user-images.githubusercontent.com/10246/177123677-9ff687de-d3b5-4224-ba61-c56b67d3d835.svg)

![org boxi Boxi](https://user-images.githubusercontent.com/10246/177123681-094e326e-93f9-4120-b7be-3f70941341c9.svg)

![org boxi Boxi Devel](https://user-images.githubusercontent.com/10246/177123684-c923805b-6cb4-4b36-bb36-692d2c8fb8f3.svg)

**Comment by garrett** [comment]
Here's a squared version:

![image](https://user-images.githubusercontent.com/10246/177153351-c16e574e-f2c7-4e36-b135-2a55ec5e1e30.png)


![org boxi Boxi Source-square](https://user-images.githubusercontent.com/10246/177152703-cea9c524-c6fc-4bdb-bf0f-61ea663f7f50.svg)

![org boxi Boxi Source-square](https://user-images.githubusercontent.com/10246/177153263-9ee8ea19-58e5-46a7-b08f-08dbb42b9b85.svg)

![org boxi Boxi Source-square Devel](https://user-images.githubusercontent.com/10246/177153183-56b330f7-8b7c-4ec7-bfad-78791190a10b.svg)

![org boxi Boxi Source-square-symbolic](https://user-images.githubusercontent.com/10246/177153194-cfc959dd-2f4c-4fdf-a388-b6b545d7e48b.svg)

And a rotated squared version:

![image](https://user-images.githubusercontent.com/10246/177153380-b854e871-a9ed-421e-a118-e4067d90d246.png)

![org boxi Boxi Source](https://user-images.githubusercontent.com/10246/177152738-87131327-9cb6-4df9-83fd-f3ce0a3b08c3.svg)

![org boxi Boxi](https://user-images.githubusercontent.com/10246/177152929-0ec97f74-5f74-4a8d-b01c-6e123017b4b0.svg)

![org boxi Boxi Devel](https://user-images.githubusercontent.com/10246/177152989-601ecac8-d5cf-4046-b18a-cfbf6556956a.svg)

![org boxi Boxi-symbolic](https://user-images.githubusercontent.com/10246/177152971-659f7788-c86f-45c0-935e-8a19c30ba257.svg)
