### ISSUE TITLE
Is there a way to choose dark theme for Boxi while gnome is using light theme?

### ISSUE THREAD

**Issue by felipehw** [allisonkarlitskaya/boxi#5]
Is there a way to choose dark theme for Boxi while Gnome is using light theme?

I'm using Gnome with light theme but my Fish shell theme is Dracula (a dark theme).

Dracula shell theme is unreadable with light background. This isn't a problem with Gnome Terminal, because I can choose dark theme for it. But I can't find a way to set dark theme for Boxi.

So, Boxi with light background (because Gnome is using light theme) turns the shell unreadable.

**Comment by allisonkarlitskaya** [comment]
Thanks for the report/question.

This doesn't exist yet, but I plan to add UI for it.

I'm on vacation right now and won't be back until mid August, though.
